task 21 - local tests passed
js-tasks-ru/js-20230117_rabinovic1944 pull request #2
Opened 2023-01-25 05:48 UTC by rabinovic1944

task 21 - local tests passed

2023-01-25 05:48 UTC, jsru commented
Добавляю преподавателя (@dosandk) для код-ревью.

2023-01-26 12:09 UTC, dosandk commented on 02-javascript-data-types/1-sort-strings/index.js
> +        const arrnew = [...arr].sort((a, b) => a.localeCompare(b,['ru-Ru','en-US'],{caseFirst:"upper"}));
пожалуйста устраните дубликаты кода:
строки 13-14 дублируют строки 18-19

2023-01-26 12:09 UTC, dosandk requested changes
необходимо внести правки согласно комментариям

2023-01-31 05:33 UTC, jsru commented
Добавляю преподавателя (@dosandk) для код-ревью.

2023-01-31 05:36 UTC, closed without merging